export interface StateCounsellingAuthority {
  state: string;
  authority: string;
  organization: string;
  ugPortal: string;
  pgPortal: string;
  officialWebsite: string;
  parentDept: string;
  coursesCovered: string;
  registrationPortal: string;
  counsellingPortal: string;
  notificationPage: string;
  contactPage: string;
  quotaType: string;
  status: string;
  verification: string;
  notes: string;
}

export const STATE_COUNSELLING_AUTHORITIES: StateCounsellingAuthority[] = [
  { state: 'Andhra Pradesh', authority: 'Dr. NTR University of Health Sciences (NTRUHS)', organization: 'Dr. NTR University of Health Sciences, Vijayawada', ugPortal: 'https://drntr.uhsap.in/', pgPortal: 'https://drntr.uhsap.in/', officialWebsite: 'https://ntruhs.ap.nic.in/', parentDept: 'Health, Medical & Family Welfare Dept., Govt. of AP', coursesCovered: 'MBBS, BDS, AYUSH (state quota), B.Sc Nursing, MD/MS, MDS, PG Diploma', registrationPortal: 'https://drntr.uhsap.in/', counsellingPortal: 'https://drntr.uhsap.in/index/Admission_counselling', notificationPage: 'https://ntruhs.ap.nic.in/', contactPage: 'https://ntruhs.ap.nic.in/', quotaType: 'State Quota (85%) + Management/NRI; AIQ 15% via MCC', status: 'Active', verification: 'Confirmed', notes: 'Same authority (NTRUHS) conducts both UG and PG counselling.' },
  { state: 'Arunachal Pradesh', authority: 'Directorate of Higher & Technical Education, Arunachal Pradesh', organization: 'Govt. of Arunachal Pradesh', ugPortal: 'https://apdhte.nic.in/', pgPortal: 'https://apdhte.nic.in/', officialWebsite: 'https://apdhte.nic.in/', parentDept: 'Dept. of Higher & Technical Education, Govt. of Arunachal Pradesh', coursesCovered: 'MBBS (limited state quota seats), B.Sc Nursing', registrationPortal: 'https://apdhte.nic.in/', counsellingPortal: 'https://apdhte.nic.in/', notificationPage: 'https://apdhte.nic.in/', contactPage: 'https://apdhte.nic.in/', quotaType: 'State Quota; most seats via AIQ/MCC given very limited medical seats', status: 'Active', verification: 'Established', notes: 'State has very few MBBS seats (TRIHMS); PG seats negligible/via DNB route.' },
  { state: 'Assam', authority: 'Directorate of Medical Education, Assam (DME Assam)', organization: 'Govt. of Assam', ugPortal: 'https://dme.assam.gov.in/', pgPortal: 'https://dme.assam.gov.in/', officialWebsite: 'https://dme.assam.gov.in/', parentDept: 'Health & Family Welfare Dept., Govt. of Assam', coursesCovered: 'MBBS, BDS, B.Sc Nursing, MD/MS, MDS, PG Diploma', registrationPortal: 'https://dme.assam.gov.in/', counsellingPortal: 'https://dme.assam.gov.in/', notificationPage: 'https://dme.assam.gov.in/', contactPage: 'https://dme.assam.gov.in/', quotaType: 'State Quota (85%) + Management/NRI; AIQ 15% via MCC', status: 'Active', verification: 'Confirmed', notes: 'Same authority (DME Assam) conducts both UG and PG counselling.' },
  { state: 'Bihar', authority: 'Bihar Combined Entrance Competitive Examination Board (BCECEB)', organization: 'Govt. of Bihar', ugPortal: 'https://bceceboard.bihar.gov.in/', pgPortal: 'https://dme.bihar.gov.in/', officialWebsite: 'https://bceceboard.bihar.gov.in/', parentDept: 'Health Dept., Govt. of Bihar', coursesCovered: 'MBBS, BDS, B.V.Sc & AH (UG via BCECEB - UGMAC); MD/MS/PG Diploma (PG via DME Bihar)', registrationPortal: 'https://bceceboard.bihar.gov.in/', counsellingPortal: 'https://bceceboard.bihar.gov.in/', notificationPage: 'https://bceceboard.bihar.gov.in/', contactPage: 'https://bceceboard.bihar.gov.in/', quotaType: 'State Quota (85%) + Management/NRI; AIQ 15% via MCC', status: 'Active', verification: 'Confirmed', notes: "UG (MBBS/BDS) via BCECEB's UGMAC counselling; PG counselling administered separately through DME Bihar - verify current PG portal each cycle." },
  { state: 'Chhattisgarh', authority: 'Directorate of Medical Education, Chhattisgarh (CG DME)', organization: 'Govt. of Chhattisgarh', ugPortal: 'https://cgdme.admissions.nic.in/', pgPortal: 'https://cgdme.admissions.nic.in/', officialWebsite: 'https://cgdme.admissions.nic.in/', parentDept: 'Health & Family Welfare Dept., Govt. of Chhattisgarh', coursesCovered: 'MBBS, BDS, B.Sc Nursing, MD/MS, MDS, PG Diploma', registrationPortal: 'https://cgdme.admissions.nic.in/', counsellingPortal: 'https://cgdme.admissions.nic.in/', notificationPage: 'https://cgdme.admissions.nic.in/', contactPage: 'https://cgdme.admissions.nic.in/', quotaType: 'State Quota (85%) + Management/NRI; AIQ 15% via MCC', status: 'Active', verification: 'Confirmed', notes: 'Same authority (CG DME) conducts both UG and PG counselling. Alternate mirrors: cgdme.in / cgdme.co.in' },
  { state: 'Goa', authority: 'Directorate of Technical Education, Goa (DTE Goa)', organization: 'Govt. of Goa', ugPortal: 'https://dte.goa.gov.in/', pgPortal: 'https://dte.goa.gov.in/', officialWebsite: 'https://dte.goa.gov.in/', parentDept: 'Dept. of Technical Education, Govt. of Goa', coursesCovered: 'MBBS, BDS, B.Sc Nursing, Allied Health, MD/MS, MDS, PG Diploma', registrationPortal: 'https://dte.goa.gov.in/', counsellingPortal: 'https://dte.goa.gov.in/', notificationPage: 'https://dte.goa.gov.in/', contactPage: 'https://dte.goa.gov.in/', quotaType: 'State Quota (85%); AIQ 15% via MCC', status: 'Active', verification: 'Confirmed', notes: 'Uncommon setup: medical counselling is run by the Technical Education directorate (single govt. medical college - Goa Medical College).' },
  { state: 'Gujarat', authority: 'Admission Committee for Professional (UG/PG) Medical Educational Courses (ACPUGMEC / ACPPGMEC)', organization: 'Govt. of Gujarat', ugPortal: 'https://medadmgujarat.org/', pgPortal: 'https://medadmgujarat.org/', officialWebsite: 'https://medadmgujarat.org/', parentDept: 'Health & Family Welfare Dept. and Medical Education Dept., Govt. of Gujarat', coursesCovered: 'MBBS, BDS, AYUSH, B.Sc Nursing, Allied Health, MD/MS, MDS, PG Diploma', registrationPortal: 'https://medadmgujarat.org/', counsellingPortal: 'https://medadmgujarat.org/', notificationPage: 'https://medadmgujarat.org/', contactPage: 'https://medadmgujarat.org/', quotaType: 'State Quota (85%) + Management/NRI; AIQ 15% via MCC', status: 'Active', verification: 'Confirmed', notes: 'ACPUGMEC handles UG, ACPPGMEC handles PG - both operate on the same medadmgujarat.org portal. Note: ACPC (acpc.gujarat.gov.in) is the SEPARATE body for engineering/other professional courses, not medical.' },
  { state: 'Haryana', authority: 'Directorate of Medical Education & Research, Haryana (DMER Haryana)', organization: 'Govt. of Haryana', ugPortal: 'https://dmer.haryana.gov.in/', pgPortal: 'https://dmer.haryana.gov.in/', officialWebsite: 'https://dmer.haryana.gov.in/', parentDept: 'Medical Education & Research Dept., Govt. of Haryana', coursesCovered: 'MBBS, BDS, AYUSH, B.Sc Nursing, MD/MS, MDS, PG Diploma', registrationPortal: 'https://dmer.haryana.gov.in/', counsellingPortal: 'https://dmer.haryana.gov.in/', notificationPage: 'https://dmer.haryana.gov.in/', contactPage: 'https://dmer.haryana.gov.in/', quotaType: 'State Quota (85%) + Management/NRI; AIQ 15% via MCC', status: 'Active', verification: 'Confirmed', notes: 'Same authority (DMER Haryana) conducts both UG and PG counselling.' },
  { state: 'Himachal Pradesh', authority: 'Atal Medical & Research University, Himachal Pradesh (AMRU)', organization: 'Govt. of Himachal Pradesh', ugPortal: 'https://amruhp.ac.in/', pgPortal: 'https://amruhp.ac.in/', officialWebsite: 'https://amruhp.ac.in/', parentDept: 'Health & Family Welfare / Medical Education & Research Dept., Govt. of HP', coursesCovered: 'MBBS, BDS, BAMS, BHMS, B.Sc Nursing, MD/MS, MDS, PG Diploma', registrationPortal: 'https://amruhp.ac.in/', counsellingPortal: 'https://amruhp.ac.in/', notificationPage: 'https://amruhp.ac.in/', contactPage: 'https://amruhp.ac.in/', quotaType: 'State Quota (85%) + Management/NRI; AIQ 15% via MCC', status: 'Active', verification: 'Confirmed', notes: 'AMRU conducts counselling on behalf of the Govt. of HP Dept. of Medical Education & Research, via a Centralised Counselling Committee. Domain is .ac.in (university), not .gov.in/.nic.in.' },
  { state: 'Jharkhand', authority: 'Jharkhand Combined Entrance Competitive Examination Board (JCECEB)', organization: 'Govt. of Jharkhand', ugPortal: 'https://jceceb.jharkhand.gov.in/', pgPortal: 'https://jceceb.jharkhand.gov.in/', officialWebsite: 'https://jceceb.jharkhand.gov.in/', parentDept: 'Health, Medical Education & Family Welfare Dept., Govt. of Jharkhand', coursesCovered: 'MBBS, BDS, B.Sc Nursing, MD/MS, MDS, PG Diploma', registrationPortal: 'https://jceceb.jharkhand.gov.in/', counsellingPortal: 'https://jceceb.jharkhand.gov.in/Links/counselling.aspx', notificationPage: 'https://jceceb.jharkhand.gov.in/', contactPage: 'https://jceceb.jharkhand.gov.in/', quotaType: 'State Quota (85%) + Management/NRI; AIQ 15% via MCC', status: 'Active', verification: 'Confirmed', notes: 'Same authority (JCECEB) conducts both UG and PG counselling.' },
  { state: 'Karnataka', authority: 'Karnataka Examinations Authority (KEA)', organization: 'Govt. of Karnataka', ugPortal: 'https://kea.kar.nic.in/', pgPortal: 'https://kea.kar.nic.in/', officialWebsite: 'https://kea.kar.nic.in/', parentDept: 'Higher Education / Medical Education Dept., Govt. of Karnataka', coursesCovered: 'MBBS, BDS, AYUSH, B.Sc Nursing, MD/MS, MDS, PG Diploma', registrationPortal: 'https://kea.kar.nic.in/', counsellingPortal: 'https://kea.kar.nic.in/', notificationPage: 'https://kea.kar.nic.in/', contactPage: 'https://kea.kar.nic.in/', quotaType: 'State Quota (85%) + Management/NRI; AIQ 15% via MCC', status: 'Active', verification: 'Confirmed', notes: 'Same authority (KEA) conducts both UG and PG counselling.' },
  { state: 'Kerala', authority: 'Commissioner for Entrance Examinations, Kerala (CEE) / Directorate of Medical Education (DME)', organization: 'Govt. of Kerala', ugPortal: 'https://cee.kerala.gov.in/', pgPortal: 'https://dme.kerala.gov.in/', officialWebsite: 'https://cee.kerala.gov.in/', parentDept: 'Health & Family Welfare Dept., Govt. of Kerala', coursesCovered: 'MBBS, BDS, AYUSH, B.Sc Nursing, MD/MS, MDS, PG Diploma', registrationPortal: 'https://cee.kerala.gov.in/', counsellingPortal: 'https://cee.kerala.gov.in/', notificationPage: 'https://cee.kerala.gov.in/', contactPage: 'https://cee.kerala.gov.in/', quotaType: 'State Quota (85%) + Management/NRI; AIQ 15% via MCC', status: 'Active', verification: 'Confirmed', notes: 'CEE Kerala conducts UG (MBBS/BDS/Ayush) counselling; DME Kerala handles in-service/PG administrative matters - verify current PG counselling conducting body each cycle.' },
  { state: 'Madhya Pradesh', authority: 'Directorate of Medical Education, Madhya Pradesh (DME MP)', organization: 'Govt. of Madhya Pradesh', ugPortal: 'https://dme.mponline.gov.in/', pgPortal: 'https://dme.mponline.gov.in/', officialWebsite: 'https://dme.mponline.gov.in/', parentDept: 'Dept. of Public Health & Medical Education, Govt. of MP', coursesCovered: 'MBBS, BDS, AYUSH, B.Sc Nursing, MD/MS, MDS, PG Diploma', registrationPortal: 'https://dme.mponline.gov.in/', counsellingPortal: 'https://dme.mponline.gov.in/', notificationPage: 'https://dme.mponline.gov.in/', contactPage: 'https://dme.mponline.gov.in/', quotaType: 'State Quota (85%) + Management/NRI; AIQ 15% via MCC', status: 'Active', verification: 'Confirmed', notes: 'Same authority (DME MP) conducts both UG and PG counselling via the MPOnline-hosted portal.' },
  { state: 'Maharashtra', authority: 'State Common Entrance Test Cell, Maharashtra (CET Cell) / DMER Maharashtra', organization: 'Govt. of Maharashtra', ugPortal: 'https://cetcell.mahacet.org/', pgPortal: 'https://cetcell.mahacet.org/', officialWebsite: 'https://cetcell.mahacet.org/', parentDept: 'Directorate of Medical Education & Research (DMER), Govt. of Maharashtra', coursesCovered: 'MBBS, BDS, AYUSH, B.Sc Nursing, MD/MS, MDS, PG Diploma', registrationPortal: 'https://cetcell.mahacet.org/', counsellingPortal: 'https://cetcell.mahacet.org/', notificationPage: 'https://cetcell.mahacet.org/', contactPage: 'https://cetcell.mahacet.org/', quotaType: 'State Quota (85%) + Management/NRI; AIQ 15% via MCC', status: 'Active', verification: 'Confirmed', notes: 'CET Cell (under DMER) conducts both UG and PG counselling (CAP rounds). Mirror sites exist: cetcell.net.in, info.mahacet.org.' },
  { state: 'Manipur', authority: 'Directorate of Health Services, Manipur', organization: 'Govt. of Manipur', ugPortal: 'https://healthmanipur.gov.in/', pgPortal: 'https://healthmanipur.gov.in/', officialWebsite: 'https://healthmanipur.gov.in/', parentDept: 'Health & Family Welfare Dept., Govt. of Manipur', coursesCovered: 'MBBS, B.Sc Nursing', registrationPortal: 'https://healthmanipur.gov.in/', counsellingPortal: 'https://healthmanipur.gov.in/', notificationPage: 'https://healthmanipur.gov.in/', contactPage: 'https://healthmanipur.gov.in/', quotaType: 'State Quota; most PG seats via AIQ/MCC given limited seats', status: 'Active', verification: 'Established', notes: 'Manipur has very limited MBBS seats (RIMS Imphal seats largely under central/AIQ arrangement); verify current cycle\'s conducting body.' },
  { state: 'Meghalaya', authority: 'Health & Family Welfare Department, Government of Meghalaya', organization: 'Govt. of Meghalaya', ugPortal: 'https://meghealth.gov.in/', pgPortal: 'https://meghealth.gov.in/', officialWebsite: 'https://meghealth.gov.in/', parentDept: 'Health & Family Welfare Dept., Govt. of Meghalaya', coursesCovered: 'MBBS (very limited state quota seats), B.Sc Nursing', registrationPortal: 'https://meghealth.gov.in/', counsellingPortal: 'https://meghealth.gov.in/', notificationPage: 'https://meghealth.gov.in/', contactPage: 'https://meghealth.gov.in/', quotaType: 'State Quota; most seats via AIQ/MCC given negligible in-state medical college capacity', status: 'Active', verification: 'Established', notes: 'NEIGRIHMS Shillong (a central institute) handles its own admissions separately from state quota counselling.' },
  { state: 'Mizoram', authority: 'Higher & Technical Education Department, Mizoram (DHTE)', organization: 'Govt. of Mizoram', ugPortal: 'https://dhte.mizoram.gov.in/', pgPortal: 'https://dhte.mizoram.gov.in/', officialWebsite: 'https://dhte.mizoram.gov.in/', parentDept: 'Higher & Technical Education Dept., Govt. of Mizoram', coursesCovered: 'MBBS (limited state quota seats), B.Sc Nursing', registrationPortal: 'https://dhte.mizoram.gov.in/', counsellingPortal: 'https://dhte.mizoram.gov.in/', notificationPage: 'https://dhte.mizoram.gov.in/', contactPage: 'https://dhte.mizoram.gov.in/', quotaType: 'State Quota; most PG seats via AIQ/MCC given very limited seats', status: 'Active', verification: 'Established', notes: 'Mizoram has minimal own medical college capacity; verify current cycle\'s conducting body.' },
  { state: 'Nagaland', authority: 'Directorate of Technical Education, Nagaland (DTE Nagaland)', organization: 'Govt. of Nagaland', ugPortal: 'https://dtenagaland.org.in/', pgPortal: 'https://dtenagaland.org.in/', officialWebsite: 'https://dtenagaland.org.in/', parentDept: 'Dept. of Technical Education, Govt. of Nagaland', coursesCovered: 'MBBS (very limited state quota seats), B.Sc Nursing', registrationPortal: 'https://dtenagaland.org.in/', counsellingPortal: 'https://dtenagaland.org.in/', notificationPage: 'https://dtenagaland.org.in/', contactPage: 'https://dtenagaland.org.in/', quotaType: 'State Quota; most seats via AIQ/MCC given negligible in-state medical college capacity', status: 'Active', verification: 'Established', notes: 'Domain is .org.in, not .gov.in/.nic.in - flagged for extra verification.' },
  { state: 'Odisha', authority: 'Directorate of Medical Education & Training, Odisha (DMET Odisha)', organization: 'Govt. of Odisha', ugPortal: 'https://dmetodisha.in/', pgPortal: 'https://dmetodisha.in/', officialWebsite: 'https://dmet.odisha.gov.in/', parentDept: 'Health & Family Welfare Dept., Govt. of Odisha', coursesCovered: 'MBBS, BDS, B.Sc Nursing, MD/MS, MDS, PG Diploma', registrationPortal: 'https://dmetodisha.in/', counsellingPortal: 'https://dmetodisha.in/', notificationPage: 'https://dmet.odisha.gov.in/', contactPage: 'https://dmet.odisha.gov.in/', quotaType: 'State Quota (85%) + Management/NRI; AIQ 15% via MCC', status: 'Active', verification: 'Confirmed', notes: 'Departmental site: dmet.odisha.gov.in; live counselling operations run on dmetodisha.in.' },
  { state: 'Punjab', authority: 'Baba Farid University of Health Sciences (BFUHS), Faridkot', organization: 'Govt. of Punjab', ugPortal: 'https://bfuhs.ac.in/', pgPortal: 'https://bfuhs.ac.in/', officialWebsite: 'https://bfuhs.ac.in/', parentDept: 'Medical Education & Research Dept., Govt. of Punjab', coursesCovered: 'MBBS, BDS, AYUSH, B.Sc Nursing, MD/MS, MDS, PG Diploma', registrationPortal: 'https://bfuhs.ac.in/', counsellingPortal: 'https://bfuhs.smartpad.in/', notificationPage: 'https://bfuhs.ac.in/', contactPage: 'https://bfuhs.ac.in/', quotaType: 'State Quota (85%) + Management/NRI (incl. CMC Ludhiana policy); AIQ 15% via MCC', status: 'Active', verification: 'Confirmed', notes: 'Same authority (BFUHS) conducts both UG and PG counselling; live counselling operations run on the bfuhs.smartpad.in sub-portal.' },
  { state: 'Rajasthan', authority: 'NEET UG/PG Medical & Dental Admission/Counselling Board, Rajasthan', organization: 'Govt. of Rajasthan (Dept. of Medical Education)', ugPortal: 'https://dme.rajasthan.gov.in/', pgPortal: 'https://dme.rajasthan.gov.in/', officialWebsite: 'https://dme.rajasthan.gov.in/', parentDept: 'Dept. of Medical Education (DME), Govt. of Rajasthan', coursesCovered: 'MBBS, BDS, MD/MS, MDS, PG Diploma', registrationPortal: 'https://dme.rajasthan.gov.in/', counsellingPortal: '(year-specific portal, e.g. rajugneet[YYYY].in - changes annually)', notificationPage: 'https://dme.rajasthan.gov.in/', contactPage: 'https://dme.rajasthan.gov.in/', quotaType: 'State Quota (85%) + Management/NRI; AIQ 15% via MCC', status: 'Active', verification: 'Established', notes: "Rajasthan's live counselling portal is hosted on a NEW domain each admission year rather than a permanent .gov.in address. Always confirm the current year's portal via the DME Rajasthan department page." },
  { state: 'Sikkim', authority: 'Health Care, Human Services & Family Welfare Department, Government of Sikkim', organization: 'Govt. of Sikkim', ugPortal: 'https://hfws.sikkim.gov.in/', pgPortal: 'https://hfws.sikkim.gov.in/', officialWebsite: 'https://hfws.sikkim.gov.in/', parentDept: 'Health Care, Human Services & Family Welfare Dept., Govt. of Sikkim', coursesCovered: 'MBBS (state domicile quota at SMIMS - a private/deemed institute), B.Sc Nursing', registrationPortal: 'https://hfws.sikkim.gov.in/', counsellingPortal: 'https://hfws.sikkim.gov.in/', notificationPage: 'https://hfws.sikkim.gov.in/', contactPage: 'https://hfws.sikkim.gov.in/', quotaType: 'State Domicile Quota (at SMIMS, private deemed university); AIQ/MCC for other-state seats', status: 'Active', verification: 'Established', notes: 'Sikkim has no state-run government medical college; SMIMS is a private/deemed institution with a state domicile quota administered by the state Health Dept.' },
  { state: 'Tamil Nadu', authority: 'Directorate of Medical Education, Tamil Nadu (DME) - Selection Committee', organization: 'Govt. of Tamil Nadu', ugPortal: 'https://tnmedicalselection.net/', pgPortal: 'https://tnmedicalselection.net/', officialWebsite: 'https://tnmedicalselection.net/', parentDept: 'Health & Family Welfare Dept., Govt. of Tamil Nadu', coursesCovered: 'MBBS, BDS, BAMS, BHMS, BUMS, BSMS, B.V.Sc & AH, B.Sc Nursing/Allied Health, MD/MS, MDS, PG Diploma, AYUSH PG', registrationPortal: 'https://tnmedicalselection.net/', counsellingPortal: 'https://tnmedicalselection.net/', notificationPage: 'https://tnmedicalselection.net/', contactPage: 'https://tnmedicalselection.net/', quotaType: 'State Quota (85%) + Management; AIQ 15% via MCC', status: 'Active', verification: 'Confirmed', notes: 'Same authority (DME Selection Committee) conducts both UG and PG counselling on the tnmedicalselection.net portal.' },
  { state: 'Telangana', authority: 'Kaloji Narayana Rao University of Health Sciences (KNRUHS)', organization: 'Govt. of Telangana', ugPortal: 'https://knruhs.telangana.gov.in/', pgPortal: 'https://knruhs.telangana.gov.in/', officialWebsite: 'https://knruhs.telangana.gov.in/', parentDept: 'Health, Medical & Family Welfare Dept., Govt. of Telangana', coursesCovered: 'MBBS, BDS, AYUSH, B.Sc Nursing, MD/MS, MDS, PG Diploma', registrationPortal: 'https://knruhs.telangana.gov.in/', counsellingPortal: 'https://knruhs.telangana.gov.in/', notificationPage: 'https://knruhs.telangana.gov.in/', contactPage: 'https://knruhs.telangana.gov.in/', quotaType: 'State Quota (85%) + Management/NRI; AIQ 15% via MCC', status: 'Active', verification: 'Established', notes: 'Same authority (KNRUHS) conducts both UG and PG counselling. Live counselling often runs on session-specific sub-portals (e.g., tsmedadm).' },
  { state: 'Tripura', authority: 'Tripura Medical Counselling Committee (TRMCC)', organization: 'Govt. of Tripura', ugPortal: 'https://trmcc.admissions.nic.in/ug-counselling/', pgPortal: 'https://trmcc.admissions.nic.in/pg-counselling/', officialWebsite: 'https://trmcc.admissions.nic.in/', parentDept: 'Directorate of Medical Education, Health & Family Welfare Dept., Govt. of Tripura', coursesCovered: 'MBBS, BDS, B.Sc Nursing, MD/MS, PG Diploma', registrationPortal: 'https://trmcc.admissions.nic.in/', counsellingPortal: 'https://trmcc.admissions.nic.in/', notificationPage: 'https://trmcc.admissions.nic.in/', contactPage: 'https://trmcc.admissions.nic.in/', quotaType: 'State Quota (85%) + Management/NRI; AIQ 15% via MCC', status: 'Active', verification: 'Confirmed', notes: 'TRMCC runs distinct, clearly separated UG and PG counselling sections on the same nic.in-hosted portal.' },
  { state: 'Uttar Pradesh', authority: 'Directorate General of Medical Education & Training, UP (DGME / DMET, Lucknow)', organization: 'Govt. of Uttar Pradesh', ugPortal: 'https://upneet.gov.in/', pgPortal: 'https://upneet.gov.in/', officialWebsite: 'https://dgme.up.gov.in/', parentDept: 'Medical Education & Training Dept., Govt. of Uttar Pradesh', coursesCovered: 'MBBS, BDS, B.Sc Nursing, MD/MS, MDS, PG Diploma', registrationPortal: 'https://upneet.gov.in/', counsellingPortal: 'https://upneet.gov.in/', notificationPage: 'https://dgme.up.gov.in/', contactPage: 'https://dgme.up.gov.in/', quotaType: 'State Quota (85%) + Management/NRI/Minority; AIQ 15% via MCC', status: 'Active', verification: 'Confirmed', notes: 'Department site: dgme.up.gov.in; live UG counselling portal: upneet.gov.in.' },
  { state: 'Uttarakhand', authority: 'HNB Uttarakhand Medical Education University (HNBUMU)', organization: 'Govt. of Uttarakhand', ugPortal: 'https://hnbumu.ac.in/', pgPortal: 'https://hnbumu.ac.in/', officialWebsite: 'https://hnbumu.ac.in/', parentDept: 'Medical Health & Family Welfare Dept., Govt. of Uttarakhand', coursesCovered: 'MBBS, BDS, BAMS, BHMS, B.Sc Nursing, MD/MS, MDS, PG Diploma', registrationPortal: 'https://hnbumu.ac.in/', counsellingPortal: 'https://hnbumu.ac.in/', notificationPage: 'https://hnbumu.ac.in/', contactPage: 'https://hnbumu.ac.in/', quotaType: 'State Quota (85%) + Management/NRI; AIQ 15% via MCC', status: 'Active', verification: 'Confirmed', notes: 'Same authority (HNBUMU) conducts both UG and PG counselling.' },
  { state: 'West Bengal', authority: 'West Bengal Medical Counselling Committee (WBMCC)', organization: 'Govt. of West Bengal', ugPortal: 'https://wbmcc.nic.in/ug-medical-dental-counselling/', pgPortal: 'https://wbmcc.nic.in/pg-medical-counselling/', officialWebsite: 'https://wbmcc.nic.in/', parentDept: 'Health & Family Welfare Dept., Govt. of West Bengal', coursesCovered: 'MBBS, BDS, AYUSH (BAMS/BHMS/BUMS/BNYS), B.Sc Nursing, MD/MS, PG Diploma, DNB', registrationPortal: 'https://wbmcc.nic.in/', counsellingPortal: 'https://wbmcc.nic.in/', notificationPage: 'https://wbmcc.nic.in/', contactPage: 'https://wbmcc.nic.in/', quotaType: 'State Quota (85%) + Management/NRI; AIQ 15% via MCC', status: 'Active', verification: 'Confirmed', notes: 'WBMCC runs clearly separated UG and PG (+ DNB) counselling sections, plus a distinct UG AYUSH counselling section, all on wbmcc.nic.in.' },
  { state: 'Andaman & Nicobar Islands', authority: 'Medical Counselling Committee (MCC) / Directorate of Health Services, A&N', organization: 'A&N Administration', ugPortal: 'https://mcc.nic.in/', pgPortal: 'https://mcc.nic.in/', officialWebsite: 'https://and.nic.in/', parentDept: 'Directorate of Health Services, A&N Administration', coursesCovered: 'MBBS (ANIIMS Port Blair)', registrationPortal: 'https://mcc.nic.in/', counsellingPortal: 'https://mcc.nic.in/', notificationPage: 'https://mcc.nic.in/', contactPage: 'https://and.nic.in/', quotaType: 'No separate state quota system - seats effectively administered via AIQ/MCC', status: 'Active', verification: 'Established', notes: 'A&N Islands has only one govt. medical college (ANIIMS); no independent large-scale state counselling body distinct from MCC/AIQ.' },
  { state: 'Chandigarh', authority: 'Government Medical College & Hospital, Sector 32, Chandigarh (GMCH-32)', organization: 'Chandigarh Administration', ugPortal: 'https://gmch.gov.in/admissions', pgPortal: 'https://gmch.gov.in/admission-mdms-2025', officialWebsite: 'https://gmch.gov.in/', parentDept: 'Chandigarh Administration (Dept. of Medical Education & Research)', coursesCovered: 'MBBS, B.Sc Nursing, MD/MS, PG Diploma', registrationPortal: 'https://gmch.gov.in/', counsellingPortal: 'https://gmch.gov.in/admissions', notificationPage: 'https://gmch.gov.in/admissions', contactPage: 'https://gmch.gov.in/', quotaType: 'State/UT Quota (85%) + Management; AIQ 15% via MCC', status: 'Active', verification: 'Confirmed', notes: 'GMCH-32 itself (not a separate board) conducts UT-quota counselling for its own MBBS/PG seats.' },
  { state: 'Dadra and Nagar Haveli and Daman and Diu', authority: 'Directorate of Medical & Health Services, DNH & DD (DMHS)', organization: 'DNH & DD Administration', ugPortal: 'https://dmhs.dnh.nic.in/', pgPortal: 'https://dmhs.dnh.nic.in/', officialWebsite: 'https://ddadmn.gov.in/', parentDept: 'DNH & DD Administration', coursesCovered: 'B.Sc Nursing, Allied Health (no state-run MBBS/BDS college in the UT)', registrationPortal: 'https://dmhs.dnh.nic.in/', counsellingPortal: 'https://dmhs.dnh.nic.in/', notificationPage: 'https://ddadmn.gov.in/', contactPage: 'https://ddadmn.gov.in/', quotaType: "No independent MBBS/BDS state quota - residents typically apply via other states' domicile/AIQ routes", status: 'Active', verification: 'Established', notes: 'The UT does not have its own government medical college.' },
  { state: 'Delhi', authority: 'Medical Counselling Committee (MCC) / Guru Gobind Singh Indraprastha University (GGSIPU)', organization: 'Directorate General of Health Services (Delhi) / GGSIPU', ugPortal: 'https://mcc.nic.in/', pgPortal: 'https://mcc.nic.in/', officialWebsite: 'https://ipu.ac.in/', parentDept: 'Health & Family Welfare Dept., Govt. of NCT of Delhi', coursesCovered: 'MBBS, BDS, B.Sc Nursing, MD/MS, MDS, PG Diploma', registrationPortal: 'https://mcc.nic.in/', counsellingPortal: 'https://ipu.ac.in/', notificationPage: 'https://mcc.nic.in/', contactPage: 'https://ipu.ac.in/', quotaType: 'No large separate 85% state quota - most Delhi govt. medical colleges covered via AIQ/MCC; GGSIPU-affiliated colleges run their own quota', status: 'Active', verification: 'Established', notes: "Delhi's arrangement is unusual: admissions split between MCC (AIQ + most central/university seats) and GGSIPU (its affiliated colleges' quota)." },
  { state: 'Jammu and Kashmir', authority: 'J&K Board of Professional Entrance Examinations (JKBOPEE)', organization: 'UT of Jammu & Kashmir', ugPortal: 'https://jkbopee.gov.in/', pgPortal: 'https://jkbopee.gov.in/', officialWebsite: 'https://jkbopee.gov.in/', parentDept: 'Health & Medical Education Dept., UT of J&K', coursesCovered: 'MBBS, BDS, AYUSH, B.Sc Nursing, MD/MS, MDS, PG Diploma', registrationPortal: 'https://jkbopee.gov.in/', counsellingPortal: 'https://jkbopee.gov.in/', notificationPage: 'https://jkbopee.gov.in/', contactPage: 'https://jkbopee.gov.in/', quotaType: 'UT Quota (J&K does NOT participate in AIQ/MCC - JKBOPEE counsels all seats)', status: 'Active', verification: 'Confirmed', notes: 'JKBOPEE conducts both UG and PG counselling for J&K, and also administers counselling for domiciles of the UT of Ladakh.' },
  { state: 'Ladakh', authority: 'J&K Board of Professional Entrance Examinations (JKBOPEE)', organization: 'UT of Ladakh (via JKBOPEE, J&K)', ugPortal: 'https://jkbopee.gov.in/', pgPortal: 'https://jkbopee.gov.in/', officialWebsite: 'https://jkbopee.gov.in/', parentDept: 'UT Administration of Ladakh (counselling delegated to JKBOPEE, J&K)', coursesCovered: 'MBBS, BDS (Ladakh domicile quota within JKBOPEE process)', registrationPortal: 'https://jkbopee.gov.in/', counsellingPortal: 'https://jkbopee.gov.in/', notificationPage: 'https://jkbopee.gov.in/', contactPage: 'https://ladakh.nic.in/', quotaType: 'UT Domicile Quota administered through JKBOPEE (Ladakh has no independent counselling board)', status: 'Active', verification: 'Established', notes: "Ladakh does not run a separate counselling authority; JKBOPEE's merit lists carry a distinct Ladakh domicile category." },
  { state: 'Lakshadweep', authority: 'Department of Health & Family Welfare / Directorate of Medical & Health Services, Lakshadweep', organization: 'Lakshadweep Administration', ugPortal: '', pgPortal: '', officialWebsite: 'https://lakshadweep.gov.in/', parentDept: 'Lakshadweep Administration', coursesCovered: 'No local MBBS/BDS/PG medical courses; candidates apply via AIQ or other states\' domicile routes', registrationPortal: 'https://lakshadweep.gov.in/', counsellingPortal: '', notificationPage: 'https://lakshadweep.gov.in/', contactPage: 'https://lakshadweep.gov.in/', quotaType: 'No independent quota - residents apply via AIQ/MCC or other-state domicile provisions', status: 'Active', verification: 'Established', notes: 'Lakshadweep has no medical college of its own and does not run a UG/PG medical counselling authority.' },
  { state: 'Puducherry', authority: 'Directorate of Health & Family Welfare Services, Puducherry', organization: 'Govt. of Puducherry', ugPortal: 'https://health.py.gov.in/', pgPortal: 'https://health.py.gov.in/', officialWebsite: 'https://health.py.gov.in/', parentDept: 'Health & Family Welfare Dept., Govt. of Puducherry', coursesCovered: 'MBBS, BDS, B.Sc Nursing, MD/MS, MDS, PG Diploma', registrationPortal: 'https://health.py.gov.in/', counsellingPortal: 'https://health.py.gov.in/', notificationPage: 'https://py.gov.in/', contactPage: 'https://py.gov.in/', quotaType: 'UT Quota (85%) for Govt. colleges (e.g. IGMC&RI) + Management/NRI; AIQ 15% via MCC', status: 'Active', verification: 'Established', notes: "JIPMER (a central/national institute in Puducherry) runs its own separate admission process and is NOT part of the UT's state-quota counselling." },
];

/**
 * Looks up the verified counselling authority for a given state/UT name.
 * Uses fuzzy, case-insensitive matching to handle naming variants the AI or
 * frontend might send (e.g. "NCT of Delhi", "J&K", "Jammu & Kashmir",
 * "Pondicherry", "Orissa").
 */
export function getAuthorityForState(rawState: string): StateCounsellingAuthority | null {
  if (!rawState) return null;
  const normalized = rawState.toLowerCase().trim();

  const aliases: Record<string, string> = {
    'nct of delhi': 'delhi',
    'new delhi': 'delhi',
    'j&k': 'jammu and kashmir',
    'jammu & kashmir': 'jammu and kashmir',
    'orissa': 'odisha',
    'pondicherry': 'puducherry',
    'uttaranchal': 'uttarakhand',
    'dadra & nagar haveli and daman & diu': 'dadra and nagar haveli and daman and diu',
    'dadra and nagar haveli': 'dadra and nagar haveli and daman and diu',
    'daman and diu': 'dadra and nagar haveli and daman and diu',
    'a&n islands': 'andaman & nicobar islands',
    'andaman and nicobar islands': 'andaman & nicobar islands',
  };

  const key = aliases[normalized] || normalized;

  return (
    STATE_COUNSELLING_AUTHORITIES.find((row) => row.state.toLowerCase() === key) ||
    STATE_COUNSELLING_AUTHORITIES.find(
      (row) => row.state.toLowerCase().includes(key) || key.includes(row.state.toLowerCase())
    ) ||
    null
  );
}